/**:
  ros__parameters:
    min_longitudinal_offset: 1.05
    max_longitudinal_offset: 1.21
    min_lateral_offset: -0.535
    max_lateral_offset: 0.695
    min_height_offset: 0.715
    max_height_offset: 0.835
