/**:
  ros__parameters:
    # version: 0.1.0 # uncomment this line in the next update of this file format. please check Readme.md
    wheel_radius: 0.2725
    wheel_width: 0.146
    wheel_base: 1.68 # between front wheel center and rear wheel center
    wheel_tread: 1.095 # between left wheel center and right wheel center
    front_overhang: 0.31 # between front wheel center and vehicle front
    rear_overhang: 0.35 # between rear wheel center and vehicle rear
    left_overhang: 0.17 # between left wheel center and vehicle left
    right_overhang: 0.17 # between right wheel center and vehicle right
    vehicle_height: 1.686 # from sd brochure
    max_steer_angle: 0.69813 # [rad], from sd vehicle interface
