sensor_kit_base_link:
  velodyne_base_link:
    x: -1.650000
    y: 0.000000
    z: -0.281000
    roll: 0.000000
    pitch: -0.000000
    yaw: -0.096000
  # default_cam_base_link:
  #   x: 0.0
  #   y: 0.0
  #   z: 0.0
  #   roll: 0.0
  #   pitch: 0.0
  #   yaw: 0.0